// <auto-generated />
using ApiTreino.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiTreino.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261002111100_SeedingSimples")]
    partial class SeedingSimples
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiTreino.Models.Intervencao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcessoId");

                    b.ToTable("Intervencoes");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Descricao = "Abriu-se o pc e verificou-se que o cabo de ligação ao ecrã estava danificado. Substitui-se o cabo.",
                            ProcessoId = -1
                        },
                        new
                        {
                            Id = -2,
                            Descricao = "Foram efetuados testes de diagnóstico. Ficou tudo operacional.",
                            ProcessoId = -1
                        },
                        new
                        {
                            Id = -3,
                            Descricao = "Levantamento de requisitos.",
                            ProcessoId = -2
                        },
                        new
                        {
                            Id = -4,
                            Descricao = "Foi desenvolvido um protótipo funcional com alguns gráficos básicos.",
                            ProcessoId = -2
                        });
                });

            modelBuilder.Entity("ApiTreino.Models.Processo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Processos");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Descricao = "A tela está avariada.",
                            Titulo = "Avaria de computador"
                        },
                        new
                        {
                            Id = -2,
                            Descricao = "Preciso de uma dashboard para visualizar as compras.",
                            Titulo = "Power BI de compras"
                        });
                });

            modelBuilder.Entity("ApiTreino.Models.Intervencao", b =>
                {
                    b.HasOne("ApiTreino.Models.Processo", "Processo")
                        .WithMany("Intervencoes")
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Processo");
                });

            modelBuilder.Entity("ApiTreino.Models.Processo", b =>
                {
                    b.Navigation("Intervencoes");
                });
#pragma warning restore 612, 618
        }
    }
}
